---
title: "mixed_effects"
output: html_document
date: "2026-04-12"
---

```{r setup, include=FALSE}
install.packages("pacman")
pacman::p_load(tidyverse, here, lme4, lmerTest, stats, kableExtra)
```

## 1. Configurations:
```{r}
source("functions.R")

assistant <- "assistant"

models <- c("google--gemma-3-4b-it",
            "google--gemma-3-12b-it",
            "google--gemma-3-27b-it")

metrics <- c("dependency_distance_mean", "doc_length")

formula_spec = "level + (1 | dialogue_id)"

output_dir <- "../../data/output/mixed_effects/"
```

## 2. Load the data:
```{r}
data <- read_csv("../../data/metrics.csv") %>%
  filter(role == assistant) %>%
  rename(level = cefr)
```


## 3. Run the analysis:

### 3.1 RQ1
```{r}
data_RQ1_EN_regular <- data %>% filter(language == "English", type == "regular")
results_RQ1_EN_regular <- fit_models(data = data_RQ1_EN_regular, models = models, metrics = metrics, output_dir = output_dir, formula_spec = formula_spec, RQ = "RQ1_EN_regular")
```

### 3.2 RQ2
```{r}
data_RQ2_LT_regular <- data %>% filter(language == "Lithuanian", type == "regular")
results_RQ2_LT_regular <- fit_models(data = data_RQ2_LT_regular, models = models, metrics = metrics, output_dir = output_dir, formula_spec = formula_spec, RQ = "RQ2_LT_regular")
```

### 3.3 RQ3
```{r}
data_RQ3_EN_constrained <- data %>% filter(language == "English", type == "constrained")
results_RQ3_EN_constrained <- fit_models(data = data_RQ3_EN_constrained, models = models, metrics = metrics, output_dir = output_dir, formula_spec = formula_spec, RQ = "RQ2_EN_constrained")

data_RQ3_LT_constrained <- data %>% filter(language == "Lithuanian", type == "constrained")
results_RQ3_LT_constrained <- fit_models(data = data_RQ3_LT_constrained, models = models, metrics = metrics, output_dir = output_dir, formula_spec = formula_spec, RQ = "RQ3_LT_constrained")
```


## 4. Pvalue adjustment:
```{r}
p_values_dir <- file.path(output_dir, "p_values")
dir.create(p_values_dir, recursive = TRUE, showWarnings = FALSE)

results_RQ1_EN_regular <- correct_pvalue(results_RQ1_EN_regular)
save_results(data = results_RQ1_EN_regular, output_dir = p_values_dir, file_name = "results_RQ1_EN_regular_pvalues.csv")

results_RQ2_LT_regular <- correct_pvalue(results_RQ2_LT_regular)
save_results(data = results_RQ2_LT_regular, output_dir = p_values_dir, file_name = "results_RQ2_LT_regular_pvalues.csv")

results_RQ3_EN_constrained <- correct_pvalue(results_RQ3_EN_constrained)
save_results(data = results_RQ3_EN_constrained, output_dir = p_values_dir, file_name = "results_RQ3_EN_constrained_pvalues.csv")

results_RQ3_LT_constrained <- correct_pvalue(results_RQ3_LT_constrained)
save_results(data = results_RQ3_LT_constrained, output_dir = p_values_dir, file_name = "results_RQ3_LT_constrained_pvalues.csv")
```

